from pass_config import POSTGRE_ADDRESS, POSTGRE_DATABASE, POSTGRE_PORT, POSTGRE_USERNAME, POSTGRE_PASSWORD, \
    ORACLE_ALIAS, ORACLE_PORT, ORACLE_USERNAME, ORACLE_PASSWORD, ORACLE_SID

AUTH_TABLE = 'kdziedzi.oracle_accounts'
AUTH_USERNAME_ATTR = 'owner_login'
AUTH_DATABASE_ATTR = 'database_name'
AUTH_SCHEMA_ATTR = 'login'

DEBUG = False
